# Generated by Django 3.1.2 on 2022-08-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0003_multistepformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='multistepformexample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='MultiStepFormModel',
        ),
        migrations.AddField(
            model_name='information',
            name='message2',
            field=models.CharField(default='ok', max_length=1000),
            preserve_default=False,
        ),
    ]
