# Generated by Django 3.1.2 on 2022-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0004_auto_20220812_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('nomDj', models.CharField(max_length=300)),
                ('prenom', models.CharField(max_length=300)),
                ('nationalite', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[('M', 'M.'), ('F', 'Mme')], max_length=1)),
                ('birth_date', models.DateField()),
                ('lieu', models.CharField(max_length=300)),
                ('email_professionnel', models.EmailField(max_length=254, null=True)),
                ('email_personnel', models.EmailField(max_length=254, null=True)),
                ('nometp', models.CharField(max_length=300)),
                ('email_personnel1', models.EmailField(max_length=254, null=True)),
                ('matricule', models.CharField(max_length=300)),
                ('Employeur', models.CharField(max_length=300)),
                ('D_affiliation', models.DateField()),
                ('D_engagement', models.DateField()),
            ],
        ),
    ]
