# Generated by Django 3.1.2 on 2022-08-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0005_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='situation',
            field=models.CharField(choices=[('célibataire', 'célibataire'), ('marié', 'marié(e)'), ('divorcé', 'divorcé(e)'), ('Veuf', 'Veuf(ve)')], default='H', max_length=20),
            preserve_default=False,
        ),
    ]
