# Generated by Django 3.1.2 on 2022-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0006_fiche_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
