# Generated by Django 3.1.2 on 2022-08-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0007_auto_20220812_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='D_affiliation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='D_engagement',
            field=models.DateField(null=True),
        ),
    ]
