# Generated by Django 3.1.2 on 2022-08-13 05:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0008_auto_20220812_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='fixe',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='fiche',
            name='fixe1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='fiche',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='fiche',
            name='mobile1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='nom',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
