# Generated by Django 3.1.2 on 2022-08-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_RP', '0009_auto_20220813_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='nomDj',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
